const filtrar = x => x.name === "e-commerce"; // ACA REALIZAMOS EL CALLBACK PARA PASARLE AL .FILTER Y QUE SOLO MUESTRE EL REPOSITORIO CON NOMBRE e-commerce

(async () => { // DEFINIMOS LA FUNCION ANONIMA AUTOEJECUTABLE
  
  // leer archivo json
  let response = await fetch("user.json"); // ACA CON EL FETCH REALIZAMO LA PETICION AL ARCHIVO USER.JSON Y ESTE LO ASIGNAMOS A LA VARIABLE RESPONSE PARA PONER EL AWAIT Y QUE SE ESPERE A LA RESPUESTA
  let user = await response.json(); // EN ESTA LINEA RECIBIMOS LA RESPUESTA DEL ARCHIVO USER.JSON Y QUE SE LEA COMO .JSON, LO ASIGNAMOS A LA VARIABLE TAMBIEN PARA QUE ESPERE LA RESPUESTA

  // consultar usuarios github
  let respuestGithub = await fetch(`https://api.github.com/users/${user.name}/repos`); // AQUI IGUAL, REALIZAMOS LA PRETICION AL API DE GITHUB Y EN LA RUTA INTERPOLAMOS EL NOMBRE DEL USUARIO PARA CONSULTAR SUS REPOSITORIOS, IGUAL DEFINIMOS A UNA VARIABLE Y USAMOS AWAIT PARA QUE ESPERE LA RESPUESTA

  let usuariogithub = await respuestGithub.json(); // EN ESTA LINEA RECIBIMOS LA RESPUESTA DEL API DE GITHUB Y QUE SE LEA COMO .JSON, LO ASIGNAMOS A LA VARIABLE TAMBIEN PARA QUE ESPERE LA RESPUESTA

  // usuariogithub DEVUELVE UN ARRAY CON OBJETOS, CADA OBJETO ES UN REPOSITORIO PUBLICO 

  usuariogithub.forEach(element => { // RECORRECOS EL ARRAY DE LOS REPOSITORIOS CON forEach
    if (element.name === "e-commerce") { // DEFINIMOS LA CONDICIONAL DE QUE SOLO MUESTRE POR CONSOLA EL REPOSITORIO QUE SE LLAME e-commerce
      console.log(element) // IMPRIMIMOS EL ELEMENTO
    }
  });

  // let data = usuariogithub.filter(filtro); // AQUI LO QUE HACEMOS ES EN VEZ DE USAR FOREACH PODEMOS DIRECTAMENTE USAR UN FILTER, EL AGREGAMOS EL METODO FILTER AL ARRAY Y LE PASAMOS EL CALLBACK DE LA PRIMERA LINEA PARA QUE MUESTRE SOLO EL REPOSITORIO BUSCADO

  // console.log(data) // IMPRIMIMOS DATA, ES DECIR EL ARRAY RESULTANTE DEL FILTRO

  // console.log(usuariogithub) 

})();


// CON PROMESAS
function pedirRepos() { // DEFINMOS LA FUNCION
    fetch("user.json") // REALIZAMOS LA PETICION AL ARCHIVO USER.JSON, EL FETCH RETORNA UNA PROMESA
        .then(respuesta => respuesta.json()) // CONSUMIMOS LA PROMESA DEL FETCH Y QUE DEVULVA EL RESULTADO EN JSON
        .then(usuario => { // RECIBIMOS LA PROMESA ANTERIOR, DONDE EL THEN RETORNA EL JSON
            let nombreUsuario = usuario.name; // ASIGNAMOS EL NOMBRE DEL USUARIO A UNA VARIABLE
            return fetch(`https://api.github.com/users/${nombreUsuario}/repos`); // REALIZAMOS LA PRETICION AL API DE GITHUB Y EN LA RUTA INTERPOLAMOS EL NOMBRE DEL USUARIO PARA CONSULTAR SUS REPOSITORIOS
        })
        .then(response => response.json()) // EL FETCH ANTERIOR RETORNA UNA PROMESA Y ESTA LA CONSUMIMOS EN ESTE THEN DONDE RETORNAMOS EN JSON
        .then(data => { // RECIBIMOS LOS DATOS 
            let filtrado = data.filter(filtrar); // REALIZAMOS EL FILTER PARA QUE SOLO MUESTRE EL REPOSITORIO CON EL NOMBRE, EL CALLBACK ESTA EN LA PRIMERA LINEA
            console.log(filtrado[0]); // IMPRIMIMOS EL RESULTADO, EL REPOSITORIO CON EL NOMBRE BUSCADO
        })
        .catch(error => { // CONSUMIMOS O RECIBIMOS EL ERROR
            console.error("Error:", error); // IMPRIMIMOS EL ERROR
        });
}
pedirRepos()





